import { roomIconVisuals, type RoomKey } from "@/rooms/registry";
import type { SiteIconKind, SiteIconVisual } from "@/lib/site-icon-types";

export type { SiteIconKind, SiteIconVisual };

export const SITE_ORIGIN = "https://objetdart-production.up.railway.app";

/**
 * Keys with a hand-written palette below. Rooms that carry a manifest declare
 * their palette in `src/rooms/<key>/room.config.ts` instead and are merged in
 * — `SiteIconKey` stays a literal union either way, so a typo at a call site
 * is still a type error.
 */
type CoreSiteIconKey =
  | "home"
  | "aphros"
  | "archive"
  | "atlas"
  | "atoms"
  | "beyond"
  | "birds"
  | "cells"
  | "tissue"
  | "coast"
  | "organics"
  | "dna"
  | "organelles"
  | "charts"
  | "molecules"
  | "dither"
  | "circularity"
  | "clouds"
  | "coin"
  | "colophon"
  | "comb"
  | "compare"
  | "earth"
  | "fire"
  | "flowers"
  | "galaxy"
  | "growth"
  | "guide"
  | "jewel"
  | "kept"
  | "light"
  | "loom"
  | "manifold"
  | "mountain"
  | "tourbillon"
  | "nucleons"
  | "ocean"
  | "overlook"
  | "plasma"
  | "pretext"
  | "pulse"
  | "quanta"
  | "quarks"
  | "reading"
  | "seed"
  | "signal"
  | "sine"
  | "space"
  | "stars"
  | "storm"
  | "tide"
  | "time"
  | "watch"
  | "waves";

const CORE_SITE_ICON_VISUALS = {
  home: {
    title: "objet d'art",
    description: "a gold medal you can hold",
    path: "/",
    shortName: "objet d'art",
    kind: "home",
    bg: "#08111c",
    bg2: "#211708",
    glow: "#e7b94e",
    accent: "#f3d37a",
    accent2: "#4fb7c8",
    ink: "#fff4cf",
  },
  aphros: {
    title: "Aphros",
    description: "foam, shells, and love",
    path: "/aphros",
    shortName: "aphros",
    kind: "aphros",
    bg: "#fbf4e7",
    bg2: "#1e5961",
    glow: "#e6b7a1",
    accent: "#f4d6c7",
    accent2: "#157983",
    ink: "#24383d",
  },
  archive: {
    title: "Archive",
    description: "the drawers of kept things",
    path: "/archive",
    shortName: "archive",
    kind: "archive",
    bg: "#17110b",
    bg2: "#4a2b16",
    glow: "#d7a45a",
    accent: "#e8c687",
    accent2: "#7c5031",
    ink: "#fff0cf",
  },
  atlas: {
    title: "Atlas",
    description: "the territories and their bearings",
    path: "/atlas/origin",
    shortName: "atlas",
    kind: "atlas",
    bg: "#102029",
    bg2: "#39462d",
    glow: "#b8c784",
    accent: "#d9d397",
    accent2: "#66a6a8",
    ink: "#edf1d0",
  },
  beyond: {
    title: "Beyond",
    description: "a novel wave field",
    path: "/beyond",
    shortName: "beyond",
    kind: "beyond",
    bg: "#080b20",
    bg2: "#2b1145",
    glow: "#8fe0e8",
    accent: "#91dfe7",
    accent2: "#e0a2ff",
    ink: "#e8f7ff",
  },
  birds: {
    title: "Birds",
    description: "a murmuration over the meadow",
    path: "/birds",
    shortName: "birds",
    kind: "growth",
    bg: "#8eb0c8",
    bg2: "#dfe6c8",
    glow: "#f4f0e0",
    accent: "#2a2a30",
    accent2: "#8fa86a",
    ink: "#1c2420",
  },
  tissue: {
    title: "Tissue",
    description: "when one becomes many",
    path: "/tissue",
    shortName: "tissue",
    kind: "circularity",
    bg: "#0b0908",
    bg2: "#2c2116",
    glow: "#e7ac52",
    accent: "#d8a95c",
    accent2: "#4e7d8c",
    ink: "#f6ead2",
  },
  cells: {
    title: "Cells",
    description: "the plasm keeps its own tide",
    path: "/cells",
    shortName: "cells",
    kind: "circularity",
    bg: "#130e0b",
    bg2: "#33241a",
    glow: "#e7ac52",
    accent: "#f2c56b",
    accent2: "#9c3d33",
    ink: "#ffedc9",
  },
  organelles: {
    title: "Organelles",
    description: "the organs before the body",
    path: "/organelles",
    shortName: "organelles",
    kind: "circularity",
    bg: "#080a0a",
    bg2: "#1c2622",
    glow: "#aad6be",
    accent: "#86baa8",
    accent2: "#e28c6c",
    ink: "#e9f4ee",
  },
  dna: {
    title: "DNA",
    description: "the ladder that copies",
    path: "/dna",
    shortName: "dna",
    kind: "growth",
    bg: "#07080c",
    bg2: "#1d2231",
    glow: "#e7ac52",
    accent: "#86baa8",
    accent2: "#96b2e2",
    ink: "#e9f1ff",
  },
  organics: {
    title: "Organics",
    description: "what carbon does when it has time",
    path: "/organics",
    shortName: "organics",
    kind: "growth",
    bg: "#0c0a09",
    bg2: "#2a201a",
    glow: "#e7ac52",
    accent: "#ded6c4",
    accent2: "#da846c",
    ink: "#f4ecdc",
  },
  molecules: {
    title: "Molecules",
    description: "what the bond holds, the solvent carries",
    path: "/molecules",
    shortName: "molecules",
    kind: "growth",
    bg: "#0e0b10",
    bg2: "#2a1f28",
    glow: "#e7ac52",
    accent: "#f2c56b",
    accent2: "#4e7d8c",
    ink: "#ffedc9",
  },
  atoms: {
    title: "Atoms",
    description: "probability breathes around a bright nucleus",
    path: "/atoms",
    shortName: "atoms",
    kind: "plasma",
    bg: "#0a0c11",
    bg2: "#1d2430",
    glow: "#e7ac52",
    accent: "#f7f3ea",
    accent2: "#6997a4",
    ink: "#fff4d6",
  },
  charts: {
    title: "Charts",
    description: "lines, candles, and oscillators",
    path: "/charts",
    shortName: "charts",
    kind: "charts",
    bg: "#071018",
    bg2: "#17221a",
    glow: "#71d6a6",
    accent: "#90e7b7",
    accent2: "#e7bc63",
    ink: "#ddffe8",
  },
  dither: {
    title: "Dither",
    description: "ordered dots, signal studies, and luminous fields",
    path: "/dither",
    shortName: "dither",
    kind: "charts",
    bg: "#0b0e0a",
    bg2: "#182015",
    glow: "#d7ff64",
    accent: "#d7ff64",
    accent2: "#79d8ff",
    ink: "#eef0dd",
  },
  circularity: {
    title: "Circularity",
    description: "circles becoming waves",
    path: "/circularity",
    shortName: "circle",
    kind: "circularity",
    bg: "#0a1120",
    bg2: "#263d55",
    glow: "#a8d7ff",
    accent: "#d0e5ff",
    accent2: "#d2ba6a",
    ink: "#edf7ff",
  },
  clouds: {
    title: "Clouds",
    description: "the air floor, four banks deep",
    path: "/clouds",
    shortName: "clouds",
    kind: "clouds",
    bg: "#182236",
    bg2: "#7b8aa3",
    glow: "#e7edf6",
    accent: "#f5f7fb",
    accent2: "#b7c6de",
    ink: "#f7fbff",
  },
  coast: {
    title: "Coast",
    description: "the beach between land and sea",
    path: "/coast",
    shortName: "coast",
    kind: "waves",
    bg: "#7eb0d4",
    bg2: "#cfe3f0",
    glow: "#fff8e8",
    accent: "#d2b98c",
    accent2: "#2e6a86",
    ink: "#1a2a30",
  },
  coin: {
    title: "Coin",
    description: "a gold medal you tilt, flip, and rub",
    path: "/coin",
    shortName: "coin",
    kind: "coin",
    bg: "#06080d",
    bg2: "#1b1305",
    glow: "#e8bd55",
    accent: "#f8d879",
    accent2: "#3d7ba7",
    ink: "#fff2bf",
  },
  comb: {
    title: "Comb",
    description: "comb the light — the cowlick stays",
    path: "/comb",
    shortName: "comb",
    kind: "stars",
    bg: "#f4ecdd",
    bg2: "#e2cfae",
    glow: "#e7b878",
    accent: "#8fb7e8",
    accent2: "#8a6ab8",
    ink: "#4a3a27",
  },
  colophon: {
    title: "Colophon",
    description: "what kept this",
    path: "/colophon",
    shortName: "colophon",
    kind: "colophon",
    bg: "#f1eadc",
    bg2: "#2d261e",
    glow: "#c28f4b",
    accent: "#2f2a21",
    accent2: "#c38f49",
    ink: "#201b14",
  },
  guide: {
    title: "Guide",
    description: "how to hold it",
    path: "/guide",
    shortName: "guide",
    kind: "colophon",
    bg: "#f1eadc",
    bg2: "#20303c",
    glow: "#c28f4b",
    accent: "#2f2a21",
    accent2: "#3f6b7d",
    ink: "#201b14",
  },
  compare: {
    title: "Compare",
    description: "two readings held to the light",
    path: "/compare",
    shortName: "compare",
    kind: "compare",
    bg: "#101018",
    bg2: "#36244a",
    glow: "#d9b2ff",
    accent: "#f0cc76",
    accent2: "#8ed6dd",
    ink: "#fff3d6",
  },
  earth: {
    title: "Earth",
    description: "strata, seismograph, and root",
    path: "/earth",
    shortName: "earth",
    kind: "earth",
    bg: "#10110c",
    bg2: "#3d3525",
    glow: "#b8986e",
    accent: "#d8bf8c",
    accent2: "#6fa575",
    ink: "#f4e9c8",
  },
  fire: {
    title: "Fire",
    description: "the element that breathes",
    path: "/fire",
    shortName: "fire",
    kind: "fire",
    bg: "#100704",
    bg2: "#3b1208",
    glow: "#ff9c42",
    accent: "#ffd36d",
    accent2: "#d0472b",
    ink: "#fff0bd",
  },
  flowers: {
    title: "Flowers",
    description: "petals and symmetry",
    path: "/flowers",
    shortName: "flowers",
    kind: "flowers",
    bg: "#120f18",
    bg2: "#2c3b25",
    glow: "#e9a9c8",
    accent: "#ffcadc",
    accent2: "#9bd58b",
    ink: "#fff1f7",
  },
  growth: {
    title: "Growth",
    description: "sigmoid, exponential, and decay",
    path: "/growth",
    shortName: "growth",
    kind: "growth",
    bg: "#0b150e",
    bg2: "#243a1f",
    glow: "#94d171",
    accent: "#c7eb98",
    accent2: "#e2bc6f",
    ink: "#efffdb",
  },
  jewel: {
    title: "Jewel",
    description: "gold and diamond sound shader",
    path: "/jewel",
    shortName: "jewel",
    kind: "jewel",
    bg: "#06080d",
    bg2: "#16233b",
    glow: "#dbe8ff",
    accent: "#f9eaa2",
    accent2: "#75d6ff",
    ink: "#ffffff",
  },
  kept: {
    title: "Kept",
    description: "a private trail of readings",
    path: "/kept",
    shortName: "kept",
    kind: "kept",
    bg: "#11141b",
    bg2: "#2d2433",
    glow: "#c7a7ff",
    accent: "#d8c4ff",
    accent2: "#e1b76a",
    ink: "#f5edff",
  },
  light: {
    title: "Light",
    description: "color music",
    path: "/light",
    shortName: "light",
    kind: "light",
    bg: "#060b18",
    bg2: "#17244c",
    glow: "#ffe780",
    accent: "#fff1a0",
    accent2: "#70d6ff",
    ink: "#fffce7",
  },
  loom: {
    title: "Loom",
    description: "one structure woven through every sense",
    path: "/loom",
    shortName: "loom",
    kind: "signal",
    bg: "#07090e",
    bg2: "#161d33",
    glow: "#f4d37a",
    accent: "#e7ac52",
    accent2: "#8fb5e8",
    ink: "#e9edf6",
  },
  manifold: {
    title: "Manifold",
    description: "every scale kept in one fold",
    path: "/manifold",
    shortName: "manifold",
    kind: "beyond",
    bg: "#04060b",
    bg2: "#131a33",
    glow: "#cfe0ff",
    accent: "#e7ac52",
    accent2: "#8fb5e8",
    ink: "#eef4ff",
  },
  mountain: {
    title: "Mountain",
    description: "the peak above the fog",
    path: "/mountain",
    shortName: "mountain",
    kind: "earth",
    bg: "#6a7a90",
    bg2: "#3a342c",
    glow: "#f0f4f8",
    accent: "#d8d5d0",
    accent2: "#8a8478",
    ink: "#f7f4ee",
  },
  tourbillon: {
    title: "Tourbillon",
    description: "a mechanical watch in three dimensions, correcting for gravity",
    path: "/tourbillon",
    shortName: "tourbillon",
    kind: "tourbillon",
    bg: "#090c11",
    bg2: "#282018",
    glow: "#e0b66a",
    accent: "#f1cf84",
    accent2: "#7ba6b8",
    ink: "#fff0ca",
  },
  ocean: {
    title: "Ocean",
    description: "open water and rivers",
    path: "/ocean",
    shortName: "ocean",
    kind: "ocean",
    bg: "#06111d",
    bg2: "#07324a",
    glow: "#59c7d7",
    accent: "#8ee4ed",
    accent2: "#d5ba73",
    ink: "#e0fbff",
  },
  overlook: {
    title: "overlook",
    description: "the whole tree kept in one glance",
    path: "/overlook",
    shortName: "overlook",
    kind: "growth",
    bg: "#04060b",
    bg2: "#101c16",
    glow: "#e7c97e",
    accent: "#f3d77a",
    accent2: "#7ea88f",
    ink: "#f2eede",
  },
  plasma: {
    title: "Plasma",
    description: "light as wave and particle",
    path: "/plasma",
    shortName: "plasma",
    kind: "plasma",
    bg: "#080710",
    bg2: "#24194a",
    glow: "#ca7dff",
    accent: "#e0a4ff",
    accent2: "#67f0cf",
    ink: "#fbebff",
  },
  pretext: {
    title: "Pretext",
    description: "playable text",
    path: "/pretext",
    shortName: "pretext",
    kind: "pretext",
    bg: "#0b1018",
    bg2: "#273041",
    glow: "#cbd6e7",
    accent: "#e7eef8",
    accent2: "#c9a45a",
    ink: "#f8fbff",
  },
  pulse: {
    title: "Pulse",
    description: "heartbeat and pattern",
    path: "/pulse",
    shortName: "pulse",
    kind: "pulse",
    bg: "#040d0c",
    bg2: "#0f2c24",
    glow: "#62efb3",
    accent: "#83ffc8",
    accent2: "#f0c665",
    ink: "#dcffec",
  },
  nucleons: {
    title: "Nucleons",
    description: "the valley makes the elements",
    path: "/nucleons",
    shortName: "nucleons",
    kind: "plasma",
    bg: "#0a0806",
    bg2: "#241a10",
    glow: "#e7ac52",
    accent: "#f2c56b",
    accent2: "#4e7d8c",
    ink: "#ffedc9",
  },
  quanta: {
    title: "Quanta",
    description: "mass buys only a moment",
    path: "/quanta",
    shortName: "quanta",
    kind: "plasma",
    bg: "#040406",
    bg2: "#141019",
    glow: "#e7ac52",
    accent: "#f2c56b",
    accent2: "#6997a4",
    ink: "#ffedc9",
  },
  quarks: {
    title: "Quarks",
    description: "nothing here can be alone",
    path: "/quarks",
    shortName: "quarks",
    kind: "plasma",
    bg: "#07080c",
    bg2: "#191320",
    glow: "#e7ac52",
    accent: "#f2c56b",
    accent2: "#4e7d8c",
    ink: "#ffedc9",
  },
  reading: {
    title: "Reading",
    description: "a reading kept on objet d'art",
    path: "/reading",
    shortName: "reading",
    kind: "reading",
    bg: "#f2eee6",
    bg2: "#1b2f3d",
    glow: "#c8732a",
    accent: "#c8732a",
    accent2: "#2c4a5c",
    ink: "#15171a",
  },
  seed: {
    title: "Seed",
    description: "an embryo in dark soil",
    path: "/seed",
    shortName: "seed",
    kind: "growth",
    bg: "#0a0e0c",
    bg2: "#1a140f",
    glow: "#f3d77a",
    accent: "#96be64",
    accent2: "#6a4a28",
    ink: "#f4ecd8",
  },
  signal: {
    title: "Signal",
    description: "music is also waves",
    path: "/signal",
    shortName: "signal",
    kind: "signal",
    bg: "#06101c",
    bg2: "#111f3b",
    glow: "#6de1ff",
    accent: "#8decff",
    accent2: "#e7b85f",
    ink: "#e9fbff",
  },
  sine: {
    title: "Sine",
    description: "a wave explorer",
    path: "/sine",
    shortName: "sine",
    kind: "sine",
    bg: "#08111c",
    bg2: "#19334b",
    glow: "#8dd9ff",
    accent: "#b4e8ff",
    accent2: "#d5bd7b",
    ink: "#eff9ff",
  },
  galaxy: {
    title: "Galaxy",
    description: "the wave the stars stream through",
    path: "/galaxy",
    shortName: "galaxy",
    kind: "stars",
    bg: "#04070f",
    bg2: "#181330",
    glow: "#7d9bd8",
    accent: "#c8732a",
    accent2: "#b9c9e8",
    ink: "#e9edf8",
  },
  space: {
    title: "Deep space",
    description: "the web that holds the light",
    path: "/space",
    shortName: "space",
    kind: "stars",
    bg: "#05060a",
    bg2: "#141b2e",
    glow: "#5b86b8",
    accent: "#c8732a",
    accent2: "#9fb9d8",
    ink: "#e6ecf6",
  },
  stars: {
    title: "Stars",
    description: "the night sky",
    path: "/stars",
    shortName: "stars",
    kind: "stars",
    bg: "#040913",
    bg2: "#102142",
    glow: "#9db8ff",
    accent: "#d2ddff",
    accent2: "#e7c56a",
    ink: "#eef3ff",
  },
  storm: {
    title: "Storm",
    description: "the wave allowed to rage",
    path: "/storm",
    shortName: "storm",
    kind: "storm",
    bg: "#070b12",
    bg2: "#1a2632",
    glow: "#a9c8d8",
    accent: "#d6e6ee",
    accent2: "#f4c763",
    ink: "#ecf8ff",
  },
  tide: {
    title: "Tide",
    description: "night sea",
    path: "/tide",
    shortName: "tide",
    kind: "tide",
    bg: "#050b14",
    bg2: "#0b2743",
    glow: "#4db5d2",
    accent: "#9ee3ef",
    accent2: "#dcb96e",
    ink: "#e5fbff",
  },
  time: {
    title: "Time",
    description: "chronograph",
    path: "/time",
    shortName: "time",
    kind: "time",
    bg: "#080d12",
    bg2: "#25251a",
    glow: "#d3b56e",
    accent: "#ead28a",
    accent2: "#84a9b8",
    ink: "#fff2c7",
  },
  watch: {
    title: "Watch",
    description: "the room",
    path: "/watch",
    shortName: "watch",
    kind: "watch",
    bg: "#070b0d",
    bg2: "#221e18",
    glow: "#dcb361",
    accent: "#edcc82",
    accent2: "#8fb3bc",
    ink: "#fff0c8",
  },
  waves: {
    title: "Waves",
    description: "the poem",
    path: "/waves",
    shortName: "waves",
    kind: "waves",
    bg: "#07101b",
    bg2: "#143046",
    glow: "#62c9de",
    accent: "#a5e7f0",
    accent2: "#dbbd72",
    ink: "#e5fbff",
  },
} as const satisfies Record<CoreSiteIconKey, SiteIconVisual>;

/** Every room key that can render an icon: hand-written palettes + manifests. */
export type SiteIconKey = CoreSiteIconKey | RoomKey;

export const SITE_ICON_VISUALS = {
  ...CORE_SITE_ICON_VISUALS,
  ...roomIconVisuals(),
} as Record<SiteIconKey, SiteIconVisual>;

export function siteIconKey(value: string | undefined): SiteIconKey {
  if (value && value in SITE_ICON_VISUALS) {
    return value as SiteIconKey;
  }
  return "home";
}

export function siteIconPath(key: SiteIconKey, asset: "icon" | "apple" | "opengraph" | "manifest"): string {
  return `/site-icons/${key}/${asset}`;
}

export function siteAppIconPath(key: SiteIconKey, size: 192 | 512): string {
  return `/site-icons/${key}/app/${size}`;
}
