// GENERATED by scripts/build-form-atlas.mjs from the syntax tree of every
// component in this repo. Do not edit by hand: change the component, then run
// `node scripts/build-form-atlas.mjs`. `npm run test:lattice-forms` fails when
// this file is stale.
import type { FormSpec } from "@/lib/lattice-forms";

export const FORM_KINDS = ["orb","star","spiral","cell","quantum","orbit","flame","drop","petal","crystal","glyph","cloud"] as const;

export const FORM_ATLAS: readonly FormSpec[] = [
 {
  "id": "air-column",
  "component": "AirColumn",
  "rooms": [
   "atmosphere"
  ],
  "noun": "a lantern",
  "tech": "webgl",
  "kind": "cloud",
  "palette": [
   "#e28c60",
   "#8fb5e8",
   "#ffcc70"
  ],
  "params": {
   "glow": 0.4,
   "spin": 0.44,
   "pulse": 0.42,
   "jitter": 0.39,
   "drift": 0.67,
   "bonds": 0.09,
   "depth": 0.45,
   "detail": 0.79,
   "facets": 3
  }
 },
 {
  "id": "aphros",
  "component": "Aphros",
  "rooms": [
   "aphros"
  ],
  "noun": "a bloom",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#523824",
   "#6b4a3f",
   "#7aa38a"
  ],
  "params": {
   "glow": 0.83,
   "spin": -0.36,
   "pulse": 0.53,
   "jitter": 0.31,
   "drift": 0.54,
   "bonds": 0.25,
   "depth": 0.82,
   "detail": 0.81,
   "facets": 7
  }
 },
 {
  "id": "archive",
  "component": "Archive",
  "rooms": [
   "archive"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#15171a",
   "#2c4a5c",
   "#e0f4dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0.25,
   "pulse": 0,
   "jitter": 0.05,
   "drift": 0.45,
   "bonds": 0.3,
   "depth": 0,
   "detail": 0.77,
   "facets": 7
  }
 },
 {
  "id": "arrival-invitation",
  "component": "ArrivalInvitation",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#27222a",
   "#a084a8",
   "#f0dcf4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0.35,
   "jitter": 0,
   "drift": 0.58,
   "bonds": 0,
   "depth": 0,
   "detail": 0.62,
   "facets": 6
  }
 },
 {
  "id": "atlas",
  "component": "Atlas",
  "rooms": [
   "atlas"
  ],
  "noun": "a natural",
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#368a94",
   "#efc55c",
   "#f5dc9a"
  ],
  "params": {
   "glow": 0.33,
   "spin": -0.25,
   "pulse": 0.37,
   "jitter": 0.27,
   "drift": 0.77,
   "bonds": 0.46,
   "depth": 0,
   "detail": 0.9,
   "facets": 5
  }
 },
 {
  "id": "atoms-field",
  "component": "AtomsField",
  "rooms": [
   "atoms"
  ],
  "noun": "an atom",
  "tech": "canvas",
  "kind": "crystal",
  "palette": [
   "#2c4a5c",
   "#e7ac52",
   "#9dc0c9"
  ],
  "params": {
   "glow": 0.5,
   "spin": 0.28,
   "pulse": 0.56,
   "jitter": 0.2,
   "drift": 0.41,
   "bonds": 0.49,
   "depth": 0,
   "detail": 0.85,
   "facets": 6
  }
 },
 {
  "id": "beam",
  "component": "Beam",
  "rooms": [
   "beam"
  ],
  "noun": "a kept sky",
  "tech": "three",
  "kind": "flame",
  "palette": [
   "#5c6494",
   "#4c961d",
   "#b08850"
  ],
  "params": {
   "glow": 0.59,
   "spin": -0.33,
   "pulse": 0.24,
   "jitter": 0.25,
   "drift": 0.63,
   "bonds": 0.37,
   "depth": 0.46,
   "detail": 0.81,
   "facets": 5
  }
 },
 {
  "id": "beyond-wave-field",
  "component": "BeyondWaveField",
  "rooms": [
   "beyond"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "cloud",
  "palette": [
   "#45bcaf",
   "#62d6ca",
   "#f4bc5d"
  ],
  "params": {
   "glow": 0.64,
   "spin": 0.27,
   "pulse": 0.45,
   "jitter": 0,
   "drift": 0.71,
   "bonds": 0,
   "depth": 0,
   "detail": 0.76,
   "facets": 6
  }
 },
 {
  "id": "candle-mark",
  "component": "CandleMark",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "flame",
  "palette": [
   "#15171a",
   "#3a3d42",
   "#c8732a"
  ],
  "params": {
   "glow": 0.69,
   "spin": 0,
   "pulse": 0.81,
   "jitter": 0.42,
   "drift": 0.64,
   "bonds": 0.26,
   "depth": 0,
   "detail": 0.67,
   "facets": 3
  }
 },
 {
  "id": "cells-plasm",
  "component": "CellsPlasm",
  "rooms": [
   "cells"
  ],
  "noun": "a cell",
  "tech": "canvas",
  "kind": "cell",
  "palette": [
   "#7a1f1f",
   "#6997a4",
   "#e7ac52"
  ],
  "params": {
   "glow": 0.63,
   "spin": 0.33,
   "pulse": 0.64,
   "jitter": 0.36,
   "drift": 0.53,
   "bonds": 0.1,
   "depth": 0,
   "detail": 0.83,
   "facets": 7
  }
 },
 {
  "id": "charts",
  "component": "Charts",
  "rooms": [
   "charts"
  ],
  "noun": "a pinned reading",
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#e86e64",
   "#ffb46e",
   "#78d2e6"
  ],
  "params": {
   "glow": 0.37,
   "spin": -0.19,
   "pulse": 0.38,
   "jitter": 0.24,
   "drift": 0.65,
   "bonds": 0.03,
   "depth": 0,
   "detail": 0.84,
   "facets": 4
  }
 },
 {
  "id": "circularity-fourier",
  "component": "CircularityFourier",
  "rooms": [
   "circularity"
  ],
  "noun": null,
  "tech": "svg",
  "kind": "cloud",
  "palette": [
   "#b7a0ff",
   "#66d4c9",
   "#f1d77c"
  ],
  "params": {
   "glow": 0.41,
   "spin": -0.57,
   "pulse": 0.34,
   "jitter": 0,
   "drift": 0.74,
   "bonds": 0.23,
   "depth": 0,
   "detail": 0.78,
   "facets": 7
  }
 },
 {
  "id": "city",
  "component": "City",
  "rooms": [
   "city"
  ],
  "noun": "a plot",
  "tech": "three",
  "kind": "crystal",
  "palette": [
   "#23244b",
   "#e7b94e",
   "#f6e6b4"
  ],
  "params": {
   "glow": 0.46,
   "spin": -0.24,
   "pulse": 0.26,
   "jitter": 0.22,
   "drift": 0.51,
   "bonds": 0.32,
   "depth": 0.35,
   "detail": 0.9,
   "facets": 3
  }
 },
 {
  "id": "clouds",
  "component": "Clouds",
  "rooms": [
   "clouds"
  ],
  "noun": null,
  "tech": "webgl",
  "kind": "cloud",
  "palette": [
   "#24406e",
   "#1a59d9",
   "#4b6fae"
  ],
  "params": {
   "glow": 0.39,
   "spin": 0.39,
   "pulse": 0.41,
   "jitter": 0.34,
   "drift": 0.68,
   "bonds": 0.07,
   "depth": 0.52,
   "detail": 0.86,
   "facets": 7
  }
 },
 {
  "id": "coast-beach",
  "component": "CoastBeach",
  "rooms": [
   "coast"
  ],
  "noun": "a shell",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#12385c",
   "#0066ff",
   "#296b8c"
  ],
  "params": {
   "glow": 0.37,
   "spin": -0.19,
   "pulse": 0.72,
   "jitter": 0.32,
   "drift": 0.56,
   "bonds": 0.34,
   "depth": 0.4,
   "detail": 0.84,
   "facets": 3
  }
 },
 {
  "id": "coin",
  "component": "Coin",
  "rooms": [
   "coin"
  ],
  "noun": null,
  "tech": "three",
  "kind": "orbit",
  "palette": [
   "#0054ab",
   "#e7b94e",
   "#ffdc8c"
  ],
  "params": {
   "glow": 0.67,
   "spin": -0.46,
   "pulse": 0.53,
   "jitter": 0,
   "drift": 0.53,
   "bonds": 0.17,
   "depth": 0.21,
   "detail": 0.77,
   "facets": 7
  }
 },
 {
  "id": "colophon",
  "component": "Colophon",
  "rooms": [
   "colophon"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#2a4a5c",
   "#a3cfcb",
   "#f4dcdc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.59,
   "facets": 7
  }
 },
 {
  "id": "comb",
  "component": "Comb",
  "rooms": [
   "comb"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "cloud",
  "palette": [
   "#3d5c8c",
   "#5b7fae",
   "#fae4b4"
  ],
  "params": {
   "glow": 0.61,
   "spin": -0.27,
   "pulse": 0.53,
   "jitter": 0.47,
   "drift": 0.59,
   "bonds": 0.3,
   "depth": 0,
   "detail": 0.79,
   "facets": 3
  }
 },
 {
  "id": "concern-field",
  "component": "ConcernField",
  "rooms": [
   "compass"
  ],
  "noun": "a kept reading",
  "tech": "svg",
  "kind": "cloud",
  "palette": [
   "#15171a",
   "#2c4a5c",
   "#c8732a"
  ],
  "params": {
   "glow": 0.6,
   "spin": 0.28,
   "pulse": 0.69,
   "jitter": 0,
   "drift": 0.64,
   "bonds": 0.14,
   "depth": 0,
   "detail": 0.78,
   "facets": 4
  }
 },
 {
  "id": "concern-sigil",
  "component": "ConcernSigil",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "cloud",
  "palette": [
   "#2c4a5c",
   "#cfc1b8",
   "#fbf8f6"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.47,
   "facets": 4
  }
 },
 {
  "id": "concern-tint",
  "component": "ConcernTint",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "cloud",
  "palette": [
   "#dc5050",
   "#c88c64",
   "#78b4dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.44,
   "bonds": 0,
   "depth": 0,
   "detail": 0.47,
   "facets": 6
  }
 },
 {
  "id": "constellation-glyph",
  "component": "ConstellationGlyph",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "star",
  "palette": [
   "#dcb4ff",
   "#ffc8aa",
   "#b4dcff"
  ],
  "params": {
   "glow": 0.77,
   "spin": 0,
   "pulse": 0.47,
   "jitter": 0,
   "drift": 0.37,
   "bonds": 0.62,
   "depth": 0,
   "detail": 0.62,
   "facets": 7
  }
 },
 {
  "id": "deep-space-web",
  "component": "DeepSpaceWeb",
  "rooms": [
   "space"
  ],
  "noun": "a galaxy",
  "tech": "webgl",
  "kind": "spiral",
  "palette": [
   "#f57021",
   "#528ffa",
   "#edb854"
  ],
  "params": {
   "glow": 0.56,
   "spin": 0.32,
   "pulse": 0.4,
   "jitter": 0.28,
   "drift": 0.4,
   "bonds": 0.24,
   "depth": 0.31,
   "detail": 0.82,
   "facets": 6
  }
 },
 {
  "id": "dither-lab",
  "component": "DitherLab",
  "rooms": [
   "dither"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#9d74ff",
   "#79d8ff",
   "#b9ff66"
  ],
  "params": {
   "glow": 0.47,
   "spin": -0.28,
   "pulse": 0.42,
   "jitter": 0,
   "drift": 0.62,
   "bonds": 0.1,
   "depth": 0,
   "detail": 0.75,
   "facets": 4
  }
 },
 {
  "id": "drop-sphere",
  "component": "DropSphere",
  "rooms": [
   "drop"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "drop",
  "palette": [
   "#4696b4",
   "#5abedc",
   "#78e6a0"
  ],
  "params": {
   "glow": 0.48,
   "spin": 0.35,
   "pulse": 0.07,
   "jitter": 0.3,
   "drift": 0.69,
   "bonds": 0.22,
   "depth": 0,
   "detail": 0.85,
   "facets": 5
  }
 },
 {
  "id": "earth",
  "component": "Earth",
  "rooms": [
   "earth"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "crystal",
  "palette": [
   "#f06f3f",
   "#d49b55",
   "#f0b66d"
  ],
  "params": {
   "glow": 0.6,
   "spin": 0.4,
   "pulse": 0.24,
   "jitter": 0,
   "drift": 0.39,
   "bonds": 0.08,
   "depth": 0,
   "detail": 0.87,
   "facets": 4
  }
 },
 {
  "id": "eigen-field",
  "component": "EigenField",
  "rooms": [
   "eigen"
  ],
  "noun": "a constraint",
  "tech": "webgl",
  "kind": "quantum",
  "palette": [
   "#c8732a",
   "#7a9aa8",
   "#9aa7b8"
  ],
  "params": {
   "glow": 0.47,
   "spin": 0.38,
   "pulse": 0.6,
   "jitter": 0.17,
   "drift": 0.69,
   "bonds": 0.13,
   "depth": 0.31,
   "detail": 0.74,
   "facets": 6
  }
 },
 {
  "id": "field-watch",
  "component": "FieldWatch",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "quantum",
  "palette": [
   "#3a3d42",
   "#e8e2d5",
   "#eee8ff"
  ],
  "params": {
   "glow": 0.61,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.44,
   "bonds": 0,
   "depth": 0,
   "detail": 0.53,
   "facets": 4
  }
 },
 {
  "id": "fire",
  "component": "Fire",
  "rooms": [
   "fire"
  ],
  "noun": null,
  "tech": "webgl",
  "kind": "flame",
  "palette": [
   "#f08d3f",
   "#f5b15a",
   "#ffdaa4"
  ],
  "params": {
   "glow": 0.51,
   "spin": 0.27,
   "pulse": 0.53,
   "jitter": 0.52,
   "drift": 0.56,
   "bonds": 0.08,
   "depth": 0.27,
   "detail": 0.8,
   "facets": 4
  }
 },
 {
  "id": "flowers-garden",
  "component": "FlowersGarden",
  "rooms": [
   "flowers"
  ],
  "noun": "a flower",
  "tech": "canvas",
  "kind": "petal",
  "palette": [
   "#4e7d8c",
   "#4e8c5a",
   "#e7ac52"
  ],
  "params": {
   "glow": 0.67,
   "spin": -0.35,
   "pulse": 0.68,
   "jitter": 0,
   "drift": 0.6,
   "bonds": 0.33,
   "depth": 0,
   "detail": 0.83,
   "facets": 5
  }
 },
 {
  "id": "galaxy-arms",
  "component": "GalaxyArms",
  "rooms": [
   "galaxy"
  ],
  "noun": "a star",
  "tech": "webgl",
  "kind": "spiral",
  "palette": [
   "#f58c38",
   "#edb854",
   "#9ebfff"
  ],
  "params": {
   "glow": 0.5,
   "spin": -0.48,
   "pulse": 0.41,
   "jitter": 0.3,
   "drift": 0.63,
   "bonds": 0.1,
   "depth": 0.24,
   "detail": 0.82,
   "facets": 3
  }
 },
 {
  "id": "gate",
  "component": "Gate",
  "rooms": [
   "gate"
  ],
  "noun": "an ion",
  "tech": "webgl",
  "kind": "flame",
  "palette": [
   "#476bb3",
   "#598cd9",
   "#7896f0"
  ],
  "params": {
   "glow": 0.61,
   "spin": -0.49,
   "pulse": 0.58,
   "jitter": 0.17,
   "drift": 0.63,
   "bonds": 0.34,
   "depth": 0.3,
   "detail": 0.78,
   "facets": 4
  }
 },
 {
  "id": "geyser",
  "component": "Geyser",
  "rooms": [
   "geyser"
  ],
  "noun": "an eruption",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#5aa89c",
   "#e88c4a",
   "#f0c690"
  ],
  "params": {
   "glow": 0.67,
   "spin": -0.34,
   "pulse": 0.36,
   "jitter": 0.41,
   "drift": 0.54,
   "bonds": 0.11,
   "depth": 0.57,
   "detail": 0.8,
   "facets": 4
  }
 },
 {
  "id": "greek-key",
  "component": "GreekKey",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "glyph",
  "palette": [
   "#15171a",
   "#848fa8",
   "#dce2f4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.58,
   "facets": 3
  }
 },
 {
  "id": "greek-key-frame",
  "component": "GreekKeyFrame",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "glyph",
  "palette": [
   "#b8693a",
   "#86a884",
   "#dcf4dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0.56,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.36,
   "bonds": 0,
   "depth": 0,
   "detail": 0.63,
   "facets": 3
  }
 },
 {
  "id": "group-field",
  "component": "GroupField",
  "rooms": [
   "group"
  ],
  "noun": "a mark",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#8c6138",
   "#c8732a",
   "#f3d77a"
  ],
  "params": {
   "glow": 0.55,
   "spin": -0.67,
   "pulse": 0.56,
   "jitter": 0.25,
   "drift": 0.59,
   "bonds": 0.1,
   "depth": 0.22,
   "detail": 0.79,
   "facets": 4
  }
 },
 {
  "id": "growth",
  "component": "Growth",
  "rooms": [
   "growth"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "petal",
  "palette": [
   "#745126",
   "#f2c35b",
   "#b8f07a"
  ],
  "params": {
   "glow": 0.65,
   "spin": -0.35,
   "pulse": 0.62,
   "jitter": 0,
   "drift": 0.56,
   "bonds": 0.13,
   "depth": 0,
   "detail": 0.85,
   "facets": 5
  }
 },
 {
  "id": "guide-first-minute",
  "component": "GuideFirstMinute",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#2a2422",
   "#a89184",
   "#f4e6dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0.55,
   "depth": 0,
   "detail": 0.36,
   "facets": 4
  }
 },
 {
  "id": "guide-grammar",
  "component": "GuideGrammar",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#222a2a",
   "#84a4a8",
   "#dcf0f4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.41,
   "facets": 3
  }
 },
 {
  "id": "guide-hero",
  "component": "GuideHero",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#22292a",
   "#84a1a8",
   "#dceef4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.44,
   "facets": 7
  }
 },
 {
  "id": "guide-room-card",
  "component": "GuideRoomCard",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#222a2a",
   "#84a4a8",
   "#dcf0f4"
  ],
  "params": {
   "glow": 0.65,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0.62,
   "depth": 0,
   "detail": 0.49,
   "facets": 6
  }
 },
 {
  "id": "guide-rooms",
  "component": "GuideRooms",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#28222a",
   "#a384a8",
   "#f2dcf4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.43,
   "facets": 7
  }
 },
 {
  "id": "guide-voice-toggle",
  "component": "GuideVoiceToggle",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#222a24",
   "#84a891",
   "#dcf4e6"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.43,
   "facets": 5
  }
 },
 {
  "id": "guide-workshop",
  "component": "GuideWorkshop",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#222a25",
   "#84a894",
   "#dcf4e8"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.43,
   "facets": 5
  }
 },
 {
  "id": "helix-ladder",
  "component": "HelixLadder",
  "rooms": [
   "dna"
  ],
  "noun": "a base pair",
  "tech": "canvas",
  "kind": "cell",
  "palette": [
   "#c85c28",
   "#e7ac52",
   "#cedefa"
  ],
  "params": {
   "glow": 0.45,
   "spin": 0.3,
   "pulse": 0.25,
   "jitter": 0.2,
   "drift": 0.6,
   "bonds": 0.43,
   "depth": 0,
   "detail": 0.81,
   "facets": 7
  }
 },
 {
  "id": "home-cabinet",
  "component": "HomeCabinet",
  "rooms": [
   "cabinet"
  ],
  "noun": "an ember",
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#e7b94e",
   "#69d8d0",
   "#a9d879"
  ],
  "params": {
   "glow": 0.6,
   "spin": -0.42,
   "pulse": 0.43,
   "jitter": 0,
   "drift": 0.73,
   "bonds": 0.25,
   "depth": 0,
   "detail": 0.81,
   "facets": 6
  }
 },
 {
  "id": "insects",
  "component": "Insects",
  "rooms": [
   "insects"
  ],
  "noun": "an insect",
  "tech": "webgl",
  "kind": "petal",
  "palette": [
   "#5c331f",
   "#8fbf72",
   "#e8b46a"
  ],
  "params": {
   "glow": 0.36,
   "spin": -0.23,
   "pulse": 0.48,
   "jitter": 0.37,
   "drift": 0.62,
   "bonds": 0.23,
   "depth": 0.28,
   "detail": 0.74,
   "facets": 6
  }
 },
 {
  "id": "instrument",
  "component": "Instrument",
  "rooms": [
   "instrument"
  ],
  "noun": null,
  "tech": "svg",
  "kind": "cloud",
  "palette": [
   "#5574f7",
   "#45b8e8",
   "#f5d65b"
  ],
  "params": {
   "glow": 0.34,
   "spin": -0.41,
   "pulse": 0.26,
   "jitter": 0,
   "drift": 0.77,
   "bonds": 0.38,
   "depth": 0,
   "detail": 0.75,
   "facets": 6
  }
 },
 {
  "id": "jewel",
  "component": "Jewel",
  "rooms": [
   "jewel"
  ],
  "noun": "a facet",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#b8860b",
   "#e7b94e",
   "#f6e6b4"
  ],
  "params": {
   "glow": 0.52,
   "spin": -0.48,
   "pulse": 0.26,
   "jitter": 0.12,
   "drift": 0.76,
   "bonds": 0.16,
   "depth": 0.18,
   "detail": 0.79,
   "facets": 6
  }
 },
 {
  "id": "kept-constellation",
  "component": "KeptConstellation",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "star",
  "palette": [
   "#081220",
   "#e8b278",
   "#aad2f0"
  ],
  "params": {
   "glow": 0.59,
   "spin": -0.23,
   "pulse": 0.23,
   "jitter": 0,
   "drift": 0.53,
   "bonds": 0.28,
   "depth": 0,
   "detail": 0.67,
   "facets": 3
  }
 },
 {
  "id": "land",
  "component": "Land",
  "rooms": [
   "land"
  ],
  "noun": "a hummock",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#3a5a24",
   "#804d1f",
   "#7fc7d6"
  ],
  "params": {
   "glow": 0.31,
   "spin": -0.26,
   "pulse": 0.42,
   "jitter": 0.07,
   "drift": 0.73,
   "bonds": 0.17,
   "depth": 0.29,
   "detail": 0.74,
   "facets": 3
  }
 },
 {
  "id": "lattice-visitors",
  "component": "LatticeVisitors",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "crystal",
  "palette": [
   "#2c2a3a",
   "#9fa3cc",
   "#f4f6ff"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.83,
   "bonds": 0,
   "depth": 0,
   "detail": 0.46,
   "facets": 6
  }
 },
 {
  "id": "let-go",
  "component": "LetGo",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#e7ac52",
   "#eadcf4",
   "#eeeadb"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.5,
   "facets": 6
  }
 },
 {
  "id": "light-instrument",
  "component": "LightInstrument",
  "rooms": [
   "light"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "flame",
  "palette": [
   "#5574f7",
   "#45b8e8",
   "#f5d65b"
  ],
  "params": {
   "glow": 0.49,
   "spin": -0.3,
   "pulse": 0.51,
   "jitter": 0,
   "drift": 0.69,
   "bonds": 0.23,
   "depth": 0,
   "detail": 0.78,
   "facets": 3
  }
 },
 {
  "id": "local-group",
  "component": "LocalGroup",
  "rooms": [
   "localgroup"
  ],
  "noun": "a galaxy",
  "tech": "webgl",
  "kind": "spiral",
  "palette": [
   "#c14fd0",
   "#6e96f0",
   "#85b8ff"
  ],
  "params": {
   "glow": 0.63,
   "spin": 0.3,
   "pulse": 0.38,
   "jitter": 0.26,
   "drift": 0.64,
   "bonds": 0.2,
   "depth": 0.29,
   "detail": 0.75,
   "facets": 5
  }
 },
 {
  "id": "manifold-fold",
  "component": "ManifoldFold",
  "rooms": [
   "manifold"
  ],
  "noun": "a mass",
  "tech": "canvas",
  "kind": "orbit",
  "palette": [
   "#5a8cbe",
   "#c8823c",
   "#e7ac52"
  ],
  "params": {
   "glow": 0.42,
   "spin": -0.39,
   "pulse": 0.62,
   "jitter": 0.04,
   "drift": 0.49,
   "bonds": 0.39,
   "depth": 0,
   "detail": 0.84,
   "facets": 6
  }
 },
 {
  "id": "marsh",
  "component": "Marsh",
  "rooms": [
   "marsh"
  ],
  "noun": "a reed",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#4a7a8a",
   "#c8945a",
   "#e8dc9a"
  ],
  "params": {
   "glow": 0.58,
   "spin": -0.31,
   "pulse": 0.61,
   "jitter": 0.39,
   "drift": 0.56,
   "bonds": 0.2,
   "depth": 0.47,
   "detail": 0.8,
   "facets": 6
  }
 },
 {
  "id": "meta-navigator",
  "component": "MetaNavigator",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#ffd28c",
   "#e0dcf4",
   "#ffecc8"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0.59,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.77,
   "bonds": 0,
   "depth": 0,
   "detail": 0.6,
   "facets": 4
  }
 },
 {
  "id": "mobile-instrument-panel",
  "component": "MobileInstrumentPanel",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "cloud",
  "palette": [
   "#c3b8cf",
   "#f4eede",
   "#f9f6fb"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.63,
   "bonds": 0,
   "depth": 0,
   "detail": 0.65,
   "facets": 7
  }
 },
 {
  "id": "molecules-field",
  "component": "MoleculesField",
  "rooms": [
   "molecules"
  ],
  "noun": "a molecule",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#6997a4",
   "#e7ac52",
   "#ddd3be"
  ],
  "params": {
   "glow": 0.51,
   "spin": -0.26,
   "pulse": 0.45,
   "jitter": 0.28,
   "drift": 0.41,
   "bonds": 0.35,
   "depth": 0,
   "detail": 0.86,
   "facets": 4
  }
 },
 {
  "id": "morph-text",
  "component": "MorphText",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#22252a",
   "#848fa8",
   "#dce2f4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0,
   "depth": 0,
   "detail": 0.45,
   "facets": 3
  }
 },
 {
  "id": "mountain-peak",
  "component": "MountainPeak",
  "rooms": [
   "mountain"
  ],
  "noun": "a cairn",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#6a7a90",
   "#ccc4b3",
   "#e8e3d4"
  ],
  "params": {
   "glow": 0.29,
   "spin": 0.22,
   "pulse": 0.61,
   "jitter": 0.36,
   "drift": 0.44,
   "bonds": 0.19,
   "depth": 0.33,
   "detail": 0.8,
   "facets": 5
  }
 },
 {
  "id": "murmuration",
  "component": "Murmuration",
  "rooms": [
   "birds"
  ],
  "noun": "a bird",
  "tech": "webgl",
  "kind": "petal",
  "palette": [
   "#0d6b8c",
   "#147a47",
   "#ebb82e"
  ],
  "params": {
   "glow": 0.37,
   "spin": -0.33,
   "pulse": 0.48,
   "jitter": 0.2,
   "drift": 0.46,
   "bonds": 0.17,
   "depth": 1,
   "detail": 0.85,
   "facets": 7
  }
 },
 {
  "id": "music-color-instrument",
  "component": "MusicColorInstrument",
  "rooms": [
   "music-color"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "cloud",
  "palette": [
   "#d83a2e",
   "#45b8e8",
   "#f5d65b"
  ],
  "params": {
   "glow": 0.25,
   "spin": -0.06,
   "pulse": 0.33,
   "jitter": 0,
   "drift": 0.51,
   "bonds": 0.23,
   "depth": 0,
   "detail": 0.75,
   "facets": 4
  }
 },
 {
  "id": "nucleons-field",
  "component": "NucleonsField",
  "rooms": [
   "nucleons"
  ],
  "noun": "a nucleus",
  "tech": "canvas",
  "kind": "quantum",
  "palette": [
   "#6997a4",
   "#f2c56b",
   "#ddd3be"
  ],
  "params": {
   "glow": 0.58,
   "spin": -0.41,
   "pulse": 0.5,
   "jitter": 0.24,
   "drift": 0.45,
   "bonds": 0.22,
   "depth": 0,
   "detail": 0.86,
   "facets": 6
  }
 },
 {
  "id": "observe",
  "component": "Observe",
  "rooms": [
   "observe"
  ],
  "noun": "a molecule",
  "tech": "webgl",
  "kind": "cloud",
  "palette": [
   "#6b4d8c",
   "#7896f0",
   "#4ad03b"
  ],
  "params": {
   "glow": 0.47,
   "spin": 0.38,
   "pulse": 0.59,
   "jitter": 0.2,
   "drift": 0.5,
   "bonds": 0.46,
   "depth": 0.5,
   "detail": 0.81,
   "facets": 6
  }
 },
 {
  "id": "ocean",
  "component": "Ocean",
  "rooms": [
   "ocean"
  ],
  "noun": "a natural",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#12576b",
   "#1e788c",
   "#e8dcbe"
  ],
  "params": {
   "glow": 0.5,
   "spin": 0.29,
   "pulse": 0.53,
   "jitter": 0.42,
   "drift": 0.57,
   "bonds": 0.11,
   "depth": 0.27,
   "detail": 0.87,
   "facets": 5
  }
 },
 {
  "id": "organelles-plasm",
  "component": "OrganellesPlasm",
  "rooms": [
   "organelles"
  ],
  "noun": "an organelle",
  "tech": "canvas",
  "kind": "cell",
  "palette": [
   "#e7ac52",
   "#cedefa",
   "#f2eee6"
  ],
  "params": {
   "glow": 0.55,
   "spin": -0.24,
   "pulse": 0.51,
   "jitter": 0.2,
   "drift": 0.68,
   "bonds": 0.15,
   "depth": 0,
   "detail": 0.81,
   "facets": 7
  }
 },
 {
  "id": "organics-field",
  "component": "OrganicsField",
  "rooms": [
   "organics"
  ],
  "noun": "a chain",
  "tech": "canvas",
  "kind": "crystal",
  "palette": [
   "#e7ac52",
   "#cedefa",
   "#eeeadb"
  ],
  "params": {
   "glow": 0.52,
   "spin": 0.47,
   "pulse": 0.63,
   "jitter": 0.23,
   "drift": 0.61,
   "bonds": 0.75,
   "depth": 0,
   "detail": 0.82,
   "facets": 6
  }
 },
 {
  "id": "overlook-tree",
  "component": "OverlookTree",
  "rooms": [
   "overlook"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "petal",
  "palette": [
   "#3c6e5f",
   "#8ca0d7",
   "#e7ac52"
  ],
  "params": {
   "glow": 0.66,
   "spin": -0.32,
   "pulse": 0.55,
   "jitter": 0,
   "drift": 0.37,
   "bonds": 0.42,
   "depth": 0,
   "detail": 0.81,
   "facets": 5
  }
 },
 {
  "id": "pebble",
  "component": "Pebble",
  "rooms": [
   "pebble"
  ],
  "noun": "a cut",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#ad4a33",
   "#9e8270",
   "#8ba0c0"
  ],
  "params": {
   "glow": 0.47,
   "spin": 0.5,
   "pulse": 0.17,
   "jitter": 0.42,
   "drift": 0.58,
   "bonds": 0.2,
   "depth": 0.77,
   "detail": 0.76,
   "facets": 4
  }
 },
 {
  "id": "per-word-hero",
  "component": "PerWordHero",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#28222a",
   "#a384a8",
   "#f2dcf4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0.34,
   "jitter": 0,
   "drift": 0.79,
   "bonds": 0,
   "depth": 0,
   "detail": 0.63,
   "facets": 6
  }
 },
 {
  "id": "phase-chart",
  "component": "PhaseChart",
  "rooms": [],
  "noun": null,
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#080c14",
   "#f4dcde",
   "#f4eede"
  ],
  "params": {
   "glow": 0.25,
   "spin": -0.32,
   "pulse": 0,
   "jitter": 0.32,
   "drift": 0.65,
   "bonds": 0,
   "depth": 0,
   "detail": 0.73,
   "facets": 3
  }
 },
 {
  "id": "planet-forge",
  "component": "PlanetForge",
  "rooms": [
   "planets"
  ],
  "noun": "a world",
  "tech": "webgl",
  "kind": "orbit",
  "palette": [
   "#090b0e",
   "#e4c8ff",
   "#f2eee6"
  ],
  "params": {
   "glow": 0.41,
   "spin": -0.49,
   "pulse": 0.37,
   "jitter": 0.21,
   "drift": 0.52,
   "bonds": 0.25,
   "depth": 0.39,
   "detail": 0.82,
   "facets": 3
  }
 },
 {
  "id": "plank",
  "component": "Plank",
  "rooms": [
   "plank"
  ],
  "noun": "a stitch of space",
  "tech": "webgl",
  "kind": "quantum",
  "palette": [
   "#0054ab",
   "#265973",
   "#7fd4c9"
  ],
  "params": {
   "glow": 0.55,
   "spin": 0.46,
   "pulse": 0.28,
   "jitter": 0.33,
   "drift": 0.7,
   "bonds": 0.34,
   "depth": 0.4,
   "detail": 0.76,
   "facets": 4
  }
 },
 {
  "id": "plasma",
  "component": "Plasma",
  "rooms": [
   "plasma"
  ],
  "noun": null,
  "tech": "webgl",
  "kind": "flame",
  "palette": [
   "#332aff",
   "#cca8ff",
   "#f6f1e0"
  ],
  "params": {
   "glow": 0.69,
   "spin": 0.38,
   "pulse": 0.38,
   "jitter": 0.15,
   "drift": 0.66,
   "bonds": 0.13,
   "depth": 0.22,
   "detail": 0.81,
   "facets": 3
  }
 },
 {
  "id": "plasma-orb",
  "component": "PlasmaOrb",
  "rooms": [
   "orb"
  ],
  "noun": "a disc",
  "tech": "webgl",
  "kind": "orbit",
  "palette": [
   "#c8732a",
   "#ffb46e",
   "#ffc8fe"
  ],
  "params": {
   "glow": 0.63,
   "spin": -0.41,
   "pulse": 0.27,
   "jitter": 0.35,
   "drift": 0.74,
   "bonds": 0.24,
   "depth": 0.45,
   "detail": 0.74,
   "facets": 4
  }
 },
 {
  "id": "pretext-wave",
  "component": "PretextWave",
  "rooms": [
   "pretext"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#c8732a",
   "#88b8d8",
   "#ffc884"
  ],
  "params": {
   "glow": 0.35,
   "spin": -0.29,
   "pulse": 0.34,
   "jitter": 0,
   "drift": 0.67,
   "bonds": 0.36,
   "depth": 0,
   "detail": 0.8,
   "facets": 4
  }
 },
 {
  "id": "pulse",
  "component": "Pulse",
  "rooms": [
   "pulse"
  ],
  "noun": "a pattern",
  "tech": "canvas",
  "kind": "cloud",
  "palette": [
   "#ff5d73",
   "#5ad1ff",
   "#f2bf62"
  ],
  "params": {
   "glow": 0.64,
   "spin": -0.37,
   "pulse": 0.91,
   "jitter": 0.06,
   "drift": 0.68,
   "bonds": 0.18,
   "depth": 0,
   "detail": 0.84,
   "facets": 6
  }
 },
 {
  "id": "quanta-field",
  "component": "QuantaField",
  "rooms": [
   "quanta"
  ],
  "noun": "a particle",
  "tech": "canvas",
  "kind": "quantum",
  "palette": [
   "#b25048",
   "#b8a87f",
   "#e7ac52"
  ],
  "params": {
   "glow": 0.49,
   "spin": 0.28,
   "pulse": 0.41,
   "jitter": 0.1,
   "drift": 0.48,
   "bonds": 0.1,
   "depth": 0,
   "detail": 0.83,
   "facets": 3
  }
 },
 {
  "id": "quarks-vacuum",
  "component": "QuarksVacuum",
  "rooms": [
   "quarks"
  ],
  "noun": "a hadron",
  "tech": "canvas",
  "kind": "quantum",
  "palette": [
   "#c8732a",
   "#e7ac52",
   "#ddd3be"
  ],
  "params": {
   "glow": 0.51,
   "spin": 0.39,
   "pulse": 0.51,
   "jitter": 0.33,
   "drift": 0.43,
   "bonds": 0.19,
   "depth": 0,
   "detail": 0.85,
   "facets": 7
  }
 },
 {
  "id": "reading",
  "component": "Reading",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#2a2226",
   "#a88492",
   "#f4dce4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.11,
   "bonds": 0.42,
   "depth": 0,
   "detail": 0.67,
   "facets": 6
  }
 },
 {
  "id": "reef",
  "component": "Reef",
  "rooms": [
   "reef"
  ],
  "noun": "a polyp",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#c26a52",
   "#e0693a",
   "#3d9ec2"
  ],
  "params": {
   "glow": 0.74,
   "spin": 0.31,
   "pulse": 0.55,
   "jitter": 0.43,
   "drift": 0.58,
   "bonds": 0.26,
   "depth": 0.83,
   "detail": 0.81,
   "facets": 5
  }
 },
 {
  "id": "relativity-room",
  "component": "RelativityRoom",
  "rooms": [
   "relativity"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "orbit",
  "palette": [
   "#e7ac52",
   "#ffc882",
   "#ffe2aa"
  ],
  "params": {
   "glow": 0.46,
   "spin": 0.35,
   "pulse": 0.49,
   "jitter": 0,
   "drift": 0.44,
   "bonds": 0.17,
   "depth": 0,
   "detail": 0.87,
   "facets": 4
  }
 },
 {
  "id": "rock-shelf",
  "component": "RockShelf",
  "rooms": [
   "rocks"
  ],
  "noun": "a stone",
  "tech": "webgl",
  "kind": "crystal",
  "palette": [
   "#6b96d1",
   "#96c4ee",
   "#f3d77a"
  ],
  "params": {
   "glow": 0.51,
   "spin": -0.42,
   "pulse": 0.44,
   "jitter": 0.24,
   "drift": 0.56,
   "bonds": 0.31,
   "depth": 0.3,
   "detail": 0.82,
   "facets": 3
  }
 },
 {
  "id": "room-help",
  "component": "RoomHelp",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#15171a",
   "#84a888",
   "#dcf4e0"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0.1,
   "pulse": 0.12,
   "jitter": 0,
   "drift": 0.48,
   "bonds": 0.31,
   "depth": 0,
   "detail": 0.68,
   "facets": 3
  }
 },
 {
  "id": "room-shell",
  "component": "RoomShell",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#22272a",
   "#8495a8",
   "#dce6f4"
  ],
  "params": {
   "glow": 0.4,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.73,
   "bonds": 0,
   "depth": 0,
   "detail": 0.63,
   "facets": 6
  }
 },
 {
  "id": "room-template",
  "component": "RoomTemplate",
  "rooms": [],
  "noun": null,
  "tech": "webgl",
  "kind": "glyph",
  "palette": [
   "#080503",
   "#84a88b",
   "#dcf4e2"
  ],
  "params": {
   "glow": 0.45,
   "spin": -0.38,
   "pulse": 0.58,
   "jitter": 0.3,
   "drift": 0.72,
   "bonds": 0.24,
   "depth": 0.14,
   "detail": 0.66,
   "facets": 3
  }
 },
 {
  "id": "root",
  "component": "Root",
  "rooms": [
   "root"
  ],
  "noun": "a tip",
  "tech": "webgl",
  "kind": "petal",
  "palette": [
   "#c26a52",
   "#4ea9a2",
   "#c8945a"
  ],
  "params": {
   "glow": 0.61,
   "spin": 0.33,
   "pulse": 0.44,
   "jitter": 0.4,
   "drift": 0.55,
   "bonds": 0.26,
   "depth": 0.51,
   "detail": 0.8,
   "facets": 7
  }
 },
 {
  "id": "route-sigil",
  "component": "RouteSigil",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "glyph",
  "palette": [
   "#2a2922",
   "#a7a884",
   "#f2f4dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0.55,
   "jitter": 0,
   "drift": 0.32,
   "bonds": 0,
   "depth": 0,
   "detail": 0.63,
   "facets": 3
  }
 },
 {
  "id": "scale-travel",
  "component": "ScaleTravel",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#090b0e",
   "#ffecc8",
   "#dcf4f0"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.74,
   "bonds": 0.59,
   "depth": 0,
   "detail": 0.72,
   "facets": 3
  }
 },
 {
  "id": "scrolling-gallery",
  "component": "ScrollingGallery",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#1b2b3f",
   "#dcf2f4",
   "#f4eede"
  ],
  "params": {
   "glow": 0.25,
   "spin": -0.12,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.63,
   "bonds": 0.44,
   "depth": 0,
   "detail": 0.66,
   "facets": 5
  }
 },
 {
  "id": "sea",
  "component": "Sea",
  "rooms": [],
  "noun": null,
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#26528c",
   "#3c78b4",
   "#5c96c3"
  ],
  "params": {
   "glow": 0.44,
   "spin": -0.07,
   "pulse": 0.67,
   "jitter": 0.39,
   "drift": 0.71,
   "bonds": 0.23,
   "depth": 0.44,
   "detail": 0.74,
   "facets": 6
  }
 },
 {
  "id": "sea-chart",
  "component": "SeaChart",
  "rooms": [],
  "noun": null,
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#15171a",
   "#2c4a5c",
   "#c8732a"
  ],
  "params": {
   "glow": 0.25,
   "spin": -0.26,
   "pulse": 0.43,
   "jitter": 0,
   "drift": 0.69,
   "bonds": 0,
   "depth": 0,
   "detail": 0.73,
   "facets": 6
  }
 },
 {
  "id": "seed-embryo",
  "component": "SeedEmbryo",
  "rooms": [
   "seed"
  ],
  "noun": "a seed",
  "tech": "canvas",
  "kind": "cell",
  "palette": [
   "#0a0e0c",
   "#d38fcb",
   "#f1e8ff"
  ],
  "params": {
   "glow": 0.38,
   "spin": -0.46,
   "pulse": 0.43,
   "jitter": 0,
   "drift": 0.5,
   "bonds": 0.15,
   "depth": 0,
   "detail": 0.72,
   "facets": 3
  }
 },
 {
  "id": "shaped-prose",
  "component": "ShapedProse",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#22222a",
   "#8884a8",
   "#e0dcf4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.36,
   "bonds": 0.52,
   "depth": 0,
   "detail": 0.57,
   "facets": 4
  }
 },
 {
  "id": "shared-reading",
  "component": "SharedReading",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#272a22",
   "#95a884",
   "#e6f4dc"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.33,
   "bonds": 0.52,
   "depth": 0,
   "detail": 0.6,
   "facets": 7
  }
 },
 {
  "id": "sigil",
  "component": "Sigil",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "glyph",
  "palette": [
   "#222a29",
   "#84a8a6",
   "#dcf4f4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0.72,
   "drift": 0.46,
   "bonds": 0,
   "depth": 0,
   "detail": 0.45,
   "facets": 5
  }
 },
 {
  "id": "signal",
  "component": "Signal",
  "rooms": [
   "signal"
  ],
  "noun": "a kept signal",
  "tech": "canvas",
  "kind": "quantum",
  "palette": [
   "#c8732a",
   "#78c8eb",
   "#ffb46e"
  ],
  "params": {
   "glow": 0.32,
   "spin": 0.25,
   "pulse": 0.23,
   "jitter": 0.07,
   "drift": 0.7,
   "bonds": 0.2,
   "depth": 0,
   "detail": 0.86,
   "facets": 7
  }
 },
 {
  "id": "sine-wave-explorer",
  "component": "SineWaveExplorer",
  "rooms": [
   "sine"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "quantum",
  "palette": [
   "#ff6f8e",
   "#65d8c5",
   "#f3d77a"
  ],
  "params": {
   "glow": 0.43,
   "spin": -0.12,
   "pulse": 0.43,
   "jitter": 0,
   "drift": 0.72,
   "bonds": 0.04,
   "depth": 0,
   "detail": 0.81,
   "facets": 6
  }
 },
 {
  "id": "site-footer",
  "component": "SiteFooter",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#2a222a",
   "#a884a4",
   "#f4dcf0"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0,
   "bonds": 0.93,
   "depth": 0,
   "detail": 0.42,
   "facets": 7
  }
 },
 {
  "id": "site-header",
  "component": "SiteHeader",
  "rooms": [],
  "noun": null,
  "tech": "svg",
  "kind": "glyph",
  "palette": [
   "#15171a",
   "#ecdcf4",
   "#e8e2d5"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0.33,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.57,
   "bonds": 0.46,
   "depth": 0,
   "detail": 0.71,
   "facets": 4
  }
 },
 {
  "id": "soil-ground",
  "component": "SoilGround",
  "rooms": [
   "soil"
  ],
  "noun": "a root",
  "tech": "webgl",
  "kind": "petal",
  "palette": [
   "#2b241d",
   "#e4d4b2",
   "#fef0ff"
  ],
  "params": {
   "glow": 0.46,
   "spin": 0.34,
   "pulse": 0.3,
   "jitter": 0.31,
   "drift": 0.58,
   "bonds": 0.38,
   "depth": 0.14,
   "detail": 0.8,
   "facets": 3
  }
 },
 {
  "id": "solar-system",
  "component": "SolarSystem",
  "rooms": [
   "solar"
  ],
  "noun": "a body",
  "tech": "webgl",
  "kind": "orbit",
  "palette": [
   "#c8732a",
   "#f2eee6",
   "#fff2c8"
  ],
  "params": {
   "glow": 0.51,
   "spin": 0.63,
   "pulse": 0.13,
   "jitter": 0.21,
   "drift": 0.49,
   "bonds": 0.21,
   "depth": 0.23,
   "detail": 0.82,
   "facets": 3
  }
 },
 {
  "id": "sound-toggle",
  "component": "SoundToggle",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#78c8eb",
   "#def4dc",
   "#f4eede"
  ],
  "params": {
   "glow": 0.25,
   "spin": -0.28,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.59,
   "bonds": 0,
   "depth": 0,
   "detail": 0.52,
   "facets": 7
  }
 },
 {
  "id": "spacetime-shader",
  "component": "SpacetimeShader",
  "rooms": [],
  "noun": null,
  "tech": "webgl",
  "kind": "quantum",
  "palette": [
   "#6bb5bd",
   "#d9a14d",
   "#ccd9ff"
  ],
  "params": {
   "glow": 0.45,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.4,
   "bonds": 0.32,
   "depth": 0.58,
   "detail": 0.66,
   "facets": 5
  }
 },
 {
  "id": "spring",
  "component": "Spring",
  "rooms": [
   "spring"
  ],
  "noun": "a seep",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#3f9dc2",
   "#69afc8",
   "#e3ac57"
  ],
  "params": {
   "glow": 0.69,
   "spin": -0.36,
   "pulse": 0.43,
   "jitter": 0.42,
   "drift": 0.57,
   "bonds": 0.18,
   "depth": 0.31,
   "detail": 0.79,
   "facets": 3
  }
 },
 {
  "id": "stars",
  "component": "Stars",
  "rooms": [
   "stars"
  ],
  "noun": "a star",
  "tech": "canvas",
  "kind": "star",
  "palette": [
   "#50321e",
   "#788cb4",
   "#b4d2ff"
  ],
  "params": {
   "glow": 0.55,
   "spin": -0.37,
   "pulse": 0.43,
   "jitter": 0.23,
   "drift": 0.75,
   "bonds": 0.21,
   "depth": 0,
   "detail": 0.94,
   "facets": 7
  }
 },
 {
  "id": "storm",
  "component": "Storm",
  "rooms": [
   "storm"
  ],
  "noun": null,
  "tech": "webgl",
  "kind": "flame",
  "palette": [
   "#1a4dd9",
   "#2a5a8c",
   "#96b4ff"
  ],
  "params": {
   "glow": 0.48,
   "spin": -0.26,
   "pulse": 0.36,
   "jitter": 0.34,
   "drift": 0.75,
   "bonds": 0.11,
   "depth": 0.17,
   "detail": 0.85,
   "facets": 6
  }
 },
 {
  "id": "structure-loom",
  "component": "StructureLoom",
  "rooms": [
   "loom"
  ],
  "noun": "a crossing",
  "tech": "canvas",
  "kind": "crystal",
  "palette": [
   "#f07878",
   "#f4d37a",
   "#e9edf6"
  ],
  "params": {
   "glow": 0.45,
   "spin": 0.21,
   "pulse": 0.45,
   "jitter": 0.11,
   "drift": 0.44,
   "bonds": 0.11,
   "depth": 0,
   "detail": 0.76,
   "facets": 3
  }
 },
 {
  "id": "tape",
  "component": "Tape",
  "rooms": [],
  "noun": null,
  "tech": "canvas",
  "kind": "glyph",
  "palette": [
   "#2c4a5c",
   "#c8732a",
   "#ffb46e"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0.6,
   "jitter": 0,
   "drift": 0.56,
   "bonds": 0,
   "depth": 0,
   "detail": 0.69,
   "facets": 5
  }
 },
 {
  "id": "threshold",
  "component": "Threshold",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#c8732a",
   "#f2eee6",
   "#dcf4f2"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0.2,
   "drift": 0.3,
   "bonds": 0.54,
   "depth": 0,
   "detail": 0.61,
   "facets": 6
  }
 },
 {
  "id": "tide",
  "component": "Tide",
  "rooms": [
   "tide"
  ],
  "noun": "a natural",
  "tech": "canvas",
  "kind": "drop",
  "palette": [
   "#5082b4",
   "#c8732a",
   "#c8965a"
  ],
  "params": {
   "glow": 0.53,
   "spin": 0.4,
   "pulse": 0.31,
   "jitter": 0.31,
   "drift": 0.69,
   "bonds": 0,
   "depth": 0,
   "detail": 0.83,
   "facets": 5
  }
 },
 {
  "id": "tidepool",
  "component": "Tidepool",
  "rooms": [
   "tidepool"
  ],
  "noun": "a creature",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#e07a3b",
   "#3d9ec2",
   "#ffd97a"
  ],
  "params": {
   "glow": 0.66,
   "spin": 0.34,
   "pulse": 0.62,
   "jitter": 0.41,
   "drift": 0.54,
   "bonds": 0.14,
   "depth": 0.76,
   "detail": 0.83,
   "facets": 4
  }
 },
 {
  "id": "timbre-instrument",
  "component": "TimbreInstrument",
  "rooms": [
   "timbre"
  ],
  "noun": null,
  "tech": "dom",
  "kind": "cloud",
  "palette": [
   "#5574f7",
   "#45b8e8",
   "#f5d65b"
  ],
  "params": {
   "glow": 0.44,
   "spin": 0.23,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.74,
   "bonds": 0.41,
   "depth": 0,
   "detail": 0.75,
   "facets": 6
  }
 },
 {
  "id": "time-manifold",
  "component": "TimeManifold",
  "rooms": [
   "time"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "orbit",
  "palette": [
   "#ff8f6a",
   "#7fb0ff",
   "#ffcf7a"
  ],
  "params": {
   "glow": 0.41,
   "spin": -0.3,
   "pulse": 0.46,
   "jitter": 0.22,
   "drift": 0.73,
   "bonds": 0.13,
   "depth": 0,
   "detail": 0.81,
   "facets": 3
  }
 },
 {
  "id": "tissue-sheet",
  "component": "TissueSheet",
  "rooms": [
   "tissue"
  ],
  "noun": "a cell",
  "tech": "canvas",
  "kind": "cell",
  "palette": [
   "#d3ca8f",
   "#cedefa",
   "#ffebe8"
  ],
  "params": {
   "glow": 0.58,
   "spin": 0.26,
   "pulse": 0.36,
   "jitter": 0.17,
   "drift": 0.27,
   "bonds": 0.31,
   "depth": 0,
   "detail": 0.83,
   "facets": 7
  }
 },
 {
  "id": "tourbillon",
  "component": "Tourbillon",
  "rooms": [
   "tourbillon"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "orbit",
  "palette": [
   "#16306b",
   "#2a52a8",
   "#6f5410"
  ],
  "params": {
   "glow": 0.35,
   "spin": 0.48,
   "pulse": 0.32,
   "jitter": 0.14,
   "drift": 0.58,
   "bonds": 0.33,
   "depth": 0,
   "detail": 0.81,
   "facets": 7
  }
 },
 {
  "id": "travel-passage-host",
  "component": "TravelPassageHost",
  "rooms": [],
  "noun": null,
  "tech": "canvas",
  "kind": "cloud",
  "palette": [
   "#403a4a",
   "#bdb8cf",
   "#f7f6fb"
  ],
  "params": {
   "glow": 0.7,
   "spin": 0.34,
   "pulse": 0.21,
   "jitter": 0.52,
   "drift": 0.27,
   "bonds": 0.42,
   "depth": 0,
   "detail": 0.93,
   "facets": 6
  }
 },
 {
  "id": "viruses",
  "component": "Viruses",
  "rooms": [
   "viruses"
  ],
  "noun": "a shell",
  "tech": "webgl",
  "kind": "cell",
  "palette": [
   "#0054ab",
   "#d689f0",
   "#7fd8d0"
  ],
  "params": {
   "glow": 0.54,
   "spin": -0.3,
   "pulse": 0.65,
   "jitter": 0.33,
   "drift": 0.66,
   "bonds": 0.15,
   "depth": 0.26,
   "detail": 0.76,
   "facets": 3
  }
 },
 {
  "id": "voids",
  "component": "Voids",
  "rooms": [
   "voids"
  ],
  "noun": "a node",
  "tech": "webgl",
  "kind": "cloud",
  "palette": [
   "#3d296b",
   "#9a7fd0",
   "#8fb6e6"
  ],
  "params": {
   "glow": 0.7,
   "spin": -0.17,
   "pulse": 0.46,
   "jitter": 0.28,
   "drift": 0.56,
   "bonds": 0.13,
   "depth": 0.27,
   "detail": 0.75,
   "facets": 6
  }
 },
 {
  "id": "watch",
  "component": "Watch",
  "rooms": [
   "watch"
  ],
  "noun": null,
  "tech": "canvas",
  "kind": "orbit",
  "palette": [
   "#c8732a",
   "#dcc8a0",
   "#ffe8b2"
  ],
  "params": {
   "glow": 0.45,
   "spin": -0.39,
   "pulse": 0.5,
   "jitter": 0.39,
   "drift": 0.8,
   "bonds": 0.22,
   "depth": 0,
   "detail": 0.84,
   "facets": 5
  }
 },
 {
  "id": "water-text",
  "component": "WaterText",
  "rooms": [],
  "noun": null,
  "tech": "dom",
  "kind": "glyph",
  "palette": [
   "#2a2226",
   "#a88492",
   "#f4dce4"
  ],
  "params": {
   "glow": 0.25,
   "spin": 0,
   "pulse": 0,
   "jitter": 0,
   "drift": 0.86,
   "bonds": 0.56,
   "depth": 0,
   "detail": 0.6,
   "facets": 6
  }
 },
 {
  "id": "waves",
  "component": "Waves",
  "rooms": [
   "waves"
  ],
  "noun": "a natural",
  "tech": "webgl",
  "kind": "drop",
  "palette": [
   "#3d4d7a",
   "#2e643e",
   "#4c961d"
  ],
  "params": {
   "glow": 0.49,
   "spin": 0.23,
   "pulse": 0.09,
   "jitter": 0.29,
   "drift": 0.59,
   "bonds": 0.36,
   "depth": 0.1,
   "detail": 0.87,
   "facets": 5
  }
 },
 {
  "id": "zeus",
  "component": "Zeus",
  "rooms": [
   "zeus"
  ],
  "noun": "a thunderhead",
  "tech": "webgl",
  "kind": "flame",
  "palette": [
   "#520f05",
   "#5285c7",
   "#8f7bff"
  ],
  "params": {
   "glow": 0.46,
   "spin": -0.29,
   "pulse": 0.44,
   "jitter": 0.54,
   "drift": 0.57,
   "bonds": 0.09,
   "depth": 0.55,
   "detail": 0.78,
   "facets": 7
  }
 }
];
